openapi: 3.0.3
info:
  title: Todo List API - Listas de Tarefas
  description: API para gerenciar listas de tarefas
  version: 1.0.0
  contact:
    email: 032758@aluno.uricer.edu.br
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /listas:
    get:
      summary: Lista todas as listas de tarefas
      operationId: listTaskLists
      responses:
        '200':
          description: Listas de tarefas obtidas com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskList'
        '500':
          description: Erro interno do servidor
    post:
      summary: Adiciona uma nova lista de tarefas
      operationId: addTaskList
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskListInput'
      responses:
        '201':
          description: Lista de tarefas adicionada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskList'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
  /listas/{id}:
    get:
      summary: Retorna uma lista de tarefas específica por ID
      operationId: getTaskListById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da lista de tarefas a ser retornada
      responses:
        '200':
          description: Lista de tarefas obtida com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskList'
        '404':
          description: Lista de tarefas não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
    put:
      summary: Atualiza uma lista de tarefas existente
      operationId: updateTaskList
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da lista de tarefas a ser atualizada
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskListInput'
      responses:
        '200':
          description: Lista de tarefas atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskList'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Lista de tarefas não encontrada
        '500':
          description: Erro interno do servidor
    delete:
      summary: Deleta uma lista de tarefas
      operationId: deleteTaskList
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da lista de tarefas a ser deletada
      responses:
        '204':
          description: Lista de tarefas deletada com sucesso
        '404':
          description: Lista de tarefas não encontrada
        '500':
          description: Erro interno do servidor
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID da tarefa
        descricao:
          type: string
          description: Descrição da tarefa
        criacao:
          type: string
          format: date
          description: Data de criação da tarefa
        limite:
          type: string
          format: date
          description: Data limite para a conclusão da tarefa
        finalizada:
          type: boolean
          description: Indica se a tarefa está concluída
        prioridade:
          type: object
          properties:
            id:
              type: integer
              description: ID da prioridade
            nivelPrioridade:
              type: string
              description: Nível da prioridade (BAIXO, MEDIO, ALTO)
        listaDeTarefas:
          type: object
          properties:
            id:
              type: integer
              description: ID da lista de tarefas
      example:
        id: 1
        descricao: Completar relatório
        criacao: "2024-05-12"
        limite: "2024-05-30"
        finalizada: false
        prioridade:
          id: 2
          nivelPrioridade: MEDIO
        listaDeTarefas:
          id: 1
    TaskList:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID da lista de tarefas
        nome:
          type: string
          description: Nome da lista de tarefas
        descricao:
          type: string
          description: Descrição da lista de tarefas
        tarefas:
          type: array
          description: Lista de tarefas associadas
          items:
            $ref: '#/components/schemas/Task'
      example:
        id: 1
        nome: "Lista Principal"
        descricao: "Esta é a lista principal de tarefas"
        tarefas:
          - id: 1
            descricao: "Completar relatório"
            criacao: "2024-05-12"
            limite: "2024-05-30"
            finalizada: false
            prioridade:
              id: 2
              nivelPrioridade: "MEDIO"
            listaDeTarefas:
              id: 1
    TaskListInput:
      type: object
      properties:
        nome:
          type: string
          description: Nome da lista de tarefas
        descricao:
          type: string
          description: Descrição da lista de tarefas
      required:
        - nome
      example:
        nome: "Lista Secundária"
        descricao: "Esta é a lista secundária de tarefas"
    Error:
      type: object
      properties:
        message:
          type: string
          description: Mensagem de erro
